# Generated by Django 3.2.9 on 2021-11-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100)),
                ('Description', models.CharField(blank=True, max_length=100)),
                ('ImgNews', models.CharField(blank=True, max_length=100)),
                ('URL', models.CharField(blank=True, max_length=100)),
                ('Source', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
